// Generated by Ignite ignite.com/cli

import { StdFee } from "@cosmjs/launchpad";
import { SigningStargateClient, DeliverTxResponse } from "@cosmjs/stargate";
import { EncodeObject, GeneratedType, OfflineSigner, Registry } from "@cosmjs/proto-signing";
import { msgTypes } from './registry';
import { IgniteClient } from "../client"
import { MissingWalletError } from "../helpers"
import { Api } from "./rest";
import { MsgDeletePost } from "./types/airhub/airhub/tx";
import { MsgAddExecutionLayer } from "./types/airhub/airhub/tx";
import { MsgUpdatePost } from "./types/airhub/airhub/tx";
import { MsgCreatePost } from "./types/airhub/airhub/tx";

import { Exelayer as typeExelayer} from "./types"
import { Params as typeParams} from "./types"
import { Post as typePost} from "./types"

export { MsgDeletePost, MsgAddExecutionLayer, MsgUpdatePost, MsgCreatePost };

type sendMsgDeletePostParams = {
  value: MsgDeletePost,
  fee?: StdFee,
  memo?: string
};

type sendMsgAddExecutionLayerParams = {
  value: MsgAddExecutionLayer,
  fee?: StdFee,
  memo?: string
};

type sendMsgUpdatePostParams = {
  value: MsgUpdatePost,
  fee?: StdFee,
  memo?: string
};

type sendMsgCreatePostParams = {
  value: MsgCreatePost,
  fee?: StdFee,
  memo?: string
};


type msgDeletePostParams = {
  value: MsgDeletePost,
};

type msgAddExecutionLayerParams = {
  value: MsgAddExecutionLayer,
};

type msgUpdatePostParams = {
  value: MsgUpdatePost,
};

type msgCreatePostParams = {
  value: MsgCreatePost,
};


export const registry = new Registry(msgTypes);

type Field = {
	name: string;
	type: unknown;
}
function getStructure(template) {
	const structure: {fields: Field[]} = { fields: [] }
	for (let [key, value] of Object.entries(template)) {
		let field = { name: key, type: typeof value }
		structure.fields.push(field)
	}
	return structure
}
const defaultFee = {
  amount: [],
  gas: "200000",
};

interface TxClientOptions {
  addr: string
	prefix: string
	signer?: OfflineSigner
}

export const txClient = ({ signer, prefix, addr }: TxClientOptions = { addr: "http://localhost:26657", prefix: "cosmos" }) => {

  return {
		
		async sendMsgDeletePost({ value, fee, memo }: sendMsgDeletePostParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgDeletePost: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry, prefix});
				let msg = this.msgDeletePost({ value: MsgDeletePost.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgDeletePost: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgAddExecutionLayer({ value, fee, memo }: sendMsgAddExecutionLayerParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgAddExecutionLayer: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry, prefix});
				let msg = this.msgAddExecutionLayer({ value: MsgAddExecutionLayer.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgAddExecutionLayer: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgUpdatePost({ value, fee, memo }: sendMsgUpdatePostParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgUpdatePost: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry, prefix});
				let msg = this.msgUpdatePost({ value: MsgUpdatePost.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgUpdatePost: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgCreatePost({ value, fee, memo }: sendMsgCreatePostParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgCreatePost: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry, prefix});
				let msg = this.msgCreatePost({ value: MsgCreatePost.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgCreatePost: Could not broadcast Tx: '+ e.message)
			}
		},
		
		
		msgDeletePost({ value }: msgDeletePostParams): EncodeObject {
			try {
				return { typeUrl: "/airhub.airhub.MsgDeletePost", value: MsgDeletePost.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgDeletePost: Could not create message: ' + e.message)
			}
		},
		
		msgAddExecutionLayer({ value }: msgAddExecutionLayerParams): EncodeObject {
			try {
				return { typeUrl: "/airhub.airhub.MsgAddExecutionLayer", value: MsgAddExecutionLayer.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgAddExecutionLayer: Could not create message: ' + e.message)
			}
		},
		
		msgUpdatePost({ value }: msgUpdatePostParams): EncodeObject {
			try {
				return { typeUrl: "/airhub.airhub.MsgUpdatePost", value: MsgUpdatePost.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgUpdatePost: Could not create message: ' + e.message)
			}
		},
		
		msgCreatePost({ value }: msgCreatePostParams): EncodeObject {
			try {
				return { typeUrl: "/airhub.airhub.MsgCreatePost", value: MsgCreatePost.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgCreatePost: Could not create message: ' + e.message)
			}
		},
		
	}
};

interface QueryClientOptions {
  addr: string
}

export const queryClient = ({ addr: addr }: QueryClientOptions = { addr: "http://localhost:1317" }) => {
  return new Api({ baseURL: addr });
};

class SDKModule {
	public query: ReturnType<typeof queryClient>;
	public tx: ReturnType<typeof txClient>;
	public structure: Record<string,unknown>;
	public registry: Array<[string, GeneratedType]> = [];

	constructor(client: IgniteClient) {		
	
		this.query = queryClient({ addr: client.env.apiURL });		
		this.updateTX(client);
		this.structure =  {
						Exelayer: getStructure(typeExelayer.fromPartial({})),
						Params: getStructure(typeParams.fromPartial({})),
						Post: getStructure(typePost.fromPartial({})),
						
		};
		client.on('signer-changed',(signer) => {			
		 this.updateTX(client);
		})
	}
	updateTX(client: IgniteClient) {
    const methods = txClient({
        signer: client.signer,
        addr: client.env.rpcURL,
        prefix: client.env.prefix ?? "cosmos",
    })
	
    this.tx = methods;
    for (let m in methods) {
        this.tx[m] = methods[m].bind(this.tx);
    }
	}
};

const Module = (test: IgniteClient) => {
	return {
		module: {
			AirhubAirhub: new SDKModule(test)
		},
		registry: msgTypes
  }
}
export default Module;